CREATE TABLE advertisements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  message TEXT NULL,
  image_url VARCHAR(255) NULL,
  media_type VARCHAR(10) NOT NULL DEFAULT 'IMAGE',
  placement VARCHAR(30) NOT NULL DEFAULT 'BELOW_STATUS',
  width_percent INT NOT NULL DEFAULT 100,
  height_px INT NOT NULL DEFAULT 320,
  link_url VARCHAR(500) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  display_order INT NOT NULL DEFAULT 0,
  starts_at DATETIME NULL,
  ends_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
