-- CREATE TABLE orders (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   customer_name VARCHAR(150) NOT NULL,
--   customer_phone VARCHAR(50),
--   status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
--   notes TEXT,
--   created_by INT,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
-- );

-- CREATE TABLE order_items (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   order_id INT NOT NULL,
--   finished_good_id INT NOT NULL,
--   qty_ordered DECIMAL(10,2) NOT NULL,
--   FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
--   FOREIGN KEY (finished_good_id) REFERENCES finished_goods(id)
-- );

-- CREATE INDEX idx_orders_status ON orders(status);
-- CREATE INDEX idx_order_items_finished_good ON order_items(finished_good_id);